vich_uploader:
    db_driver: orm

    mappings:
        argonaute:
            uri_prefix: /images/argonautes
            upload_destination: '%kernel.project_dir%/public/images/argonautes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

